Add trailing_zeros.rb
lv-390-ruby/codewars_tasks pull request #68
Opened 2019-03-28 18:27 UTC by kmandziy

2019-03-28 20:52 UTC, AlinaKovtun requested changes

2019-03-28 20:52 UTC, AlinaKovtun commented on Tasks/trailing_zeros.rb
> +def zeros(n)
Method parameter must be at least 3 characters long.

2019-03-28 20:52 UTC, AlinaKovtun commented on Tasks/trailing_zeros.rb
> +
Unnecessary blank line at the beginning of the source.

2019-03-28 20:59 UTC, AlinaKovtun approved these changes

2019-03-28 22:00 UTC, AlinaKovtun approved these changes

2019-03-29 10:00 UTC, nataliakozoriz approved these changes

2019-03-29 10:02 UTC, merged